name: Java CI with Maven

on:
  pull_request:
    branches:
      - main  # Or master, depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest  # This specifies the OS environment for running the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This action checks out the repository to the runner

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # You can modify this version if necessary

    - name: Build with Maven
      run: mvn clean install  # This will clean the project and run Maven's build process

    - name: Run tests with Maven
      run: mvn test  # This will run the unit tests using Maven
