name: Java CI with Maven

on:
  pull_request:
    branches:
      - main  # This will run the workflow when a PR is created to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu environment to run the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checks out the repository

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'  # Set the Java version (change it to the version you are using)
        distribution: 'adoptopenjdk'  # Specify the distribution of Java

    - name: Build with Maven
      run: mvn clean install  # Clean the project and install dependencies

    - name: Run tests with Maven
      run: mvn test  # Run the tests with Maven
