name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'  # Use 'temurin' (AdoptOpenJDK) or 'zulu' for JDK distribution
        java-version: '11'  # Use the appropriate Java version

    - name: Build with Maven
      run: mvn -f "Assignment 2/pom.xml" clean install  # Fixed the path to pom.xml

    - name: Run Tests
      run: mvn -f "Assignment 2/pom.xml" test  # Run tests with the correct pom.xml path
